# Generated by Django 3.0 on 2022-04-27 15:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='website',
        ),
    ]
