"""
Django settings for crm project.

Generated by 'django-admin startproject' using Django 3.0.

For more information on this file, see
https://docs.djangoproject.com/en/3.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.0/ref/settings/
"""

import os

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

#STRIPE 
STRIPE_PUB_KEY = 'pk_test_51KoSb5FypzGlH8VDr3JjHJXBXADAXhE6rt8vfMlbtgVhp2QfZ7LfNnrwzN1EPyyhTSKKaEzLa2ZzvANLAVBU8Hux002vnPbJpA'
STRIPE_SECRET_KEY = 'sk_test_51KoSb5FypzGlH8VD2HT6DZlcnkegzIDT4xOJLP590eknOD2GzTNGbhOcYeMtpAhZ30Zzm8NjZt6Zhqj7nyWCBuMH00uANgFHHm'

STRIPE_PRICE_ID_SMALL_TEAM = 'price_1Kw01VFypzGlH8VD0HfBXLFt'
STRIPE_PRICE_ID_BIG_TEAM = 'price_1Kw02eFypzGlH8VD06OkdF20'

STRIPE_WEBHOOK_KEY = 'whsec_79c057891d5e0521d61abf42769a84dc45999d12eaaf661409536228b40b4bad'

FRONTEND_WEBSITE_SUCCESS_URL = 'http://localhost:8080/dashboard/teams/plans-thank-you'
FRONTEND_WEBSITE_CANCEL_URL = 'http://localhost:8080/dashboard/teams/plans'
# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/3.0/howto/deployment/checklist/



# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'vdo6@h*o9)(xk3+6(_%2x!4f!$*x)3)q3kmyij=!azejtxa^xh'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []
# we are trying to fetch from localhost 8080 to the other url ex. localhost:3000. so from localhost:8080 to localhost:3000
# an error might come no access control allow origin means it is not getting the right url
CORS_ALLOWED_ORIGINS = [  #we allow request from other urls   
    'http://localhost:8080',

]

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework.authentication.TokenAuthentication',
        'rest_framework.authentication.SessionAuthentication',
        
    ),
    'DEFAULT_PERMISSION_CLASSES': (
        'rest_framework.permissions.IsAuthenticated',
    )
}


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    'rest_framework',
    'rest_framework.authtoken',
    'corsheaders',
    'djoser',
    'lead.apps.LeadConfig',
    'team.apps.TeamConfig',
    'client.apps.ClientConfig',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'corsheaders.middleware.CorsMiddleware', 
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'crm.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'crm.wsgi.application'


# Database
# https://docs.djangoproject.com/en/3.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': os.path.join(BASE_DIR, 'db.sqlite3'),
    }
}


# Password validation
# https://docs.djangoproject.com/en/3.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/3.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/3.0/howto/static-files/

STATIC_URL = '/static/'
